FROM eclipse-temurin:17-jre
MAINTAINER ruoyi

RUN mkdir -p /home/ruoyi
WORKDIR /home/ruoyi
COPY ./jar/ruoyi-modules-file.jar /home/ruoyi/ruoyi-modules-file.jar
ENTRYPOINT ["java","-jar","ruoyi-modules-file.jar"]
