FROM eclipse-temurin:17-jre
MAINTAINER ruoyi

RUN mkdir -p /home/ruoyi
WORKDIR /home/ruoyi
COPY ./jar/ruoyi-modules-system.jar /home/ruoyi/ruoyi-modules-system.jar
ENTRYPOINT ["java","-jar","ruoyi-modules-system.jar"]
